In [1]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
data = load_breast_cancer()
x = data.data
y = data.target

In [3]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=42)

In [4]:
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
svm_clf = SVC(kernel='rbf', probability=True, random_state=42)
knn_clf = KNeighborsClassifier(n_neighbors=5)

In [5]:
rf_clf.fit(x_train, y_train)
svm_clf.fit(x_train, y_train)
knn_clf.fit(x_train, y_train)

KNeighborsClassifier()

In [6]:
y_pred_rf = rf_clf.predict(x_val)
y_pred_svm = svm_clf.predict(x_val)
y_pred_knn = knn_clf.predict(x_val)

In [7]:
def evaluate_individual_model(y_true, y_pred, model_name):
    accuracy = accuracy_score(y_true, y_pred)
    print(f"Accuracy of {model_name} Model: {accuracy}")
    conf_mat = confusion_matrix(y_true, y_pred)
    print(f"Confusion Matrix for {model_name} Model:\n{conf_mat}")
    class_report = classification_report(y_true, y_pred)
    print(f"Classification Report for {model_name} Model:\n{class_report}")

In [8]:
evaluate_individual_model(y_val, y_pred_rf, "Random Forest")
evaluate_individual_model(y_val, y_pred_svm, "SVM")
evaluate_individual_model(y_val, y_pred_knn, "KNN")

Accuracy of Random Forest Model: 0.9649122807017544
Confusion Matrix for Random Forest Model:
[[40  3]
 [ 1 70]]
Classification Report for Random Forest Model:
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        43
           1       0.96      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

Accuracy of SVM Model: 0.9473684210526315
Confusion Matrix for SVM Model:
[[37  6]
 [ 0 71]]
Classification Report for SVM Model:
              precision    recall  f1-score   support

           0       1.00      0.86      0.93        43
           1       0.92      1.00      0.96        71

    accuracy                           0.95       114
   macro avg       0.96      0.93      0.94       114
weighted avg       0.95      0.95      0.95       114

Accuracy of KNN Model: 0.956140350877193
Confusion Matri

### Max Voting Ensemble Model

In [9]:
voting_clf = VotingClassifier(estimators=[('rf', rf_clf), ('svm', svm_clf), ('knn', knn_clf)], voting='soft')

In [10]:
voting_clf.fit(x_train, y_train)

VotingClassifier(estimators=[('rf', RandomForestClassifier(random_state=42)),
                             ('svm', SVC(probability=True, random_state=42)),
                             ('knn', KNeighborsClassifier())],
                 voting='soft')

In [11]:
y_pred = voting_clf.predict(x_val)

In [12]:
voting_clf = VotingClassifier(estimators=[('rf', rf_clf), ('svm', svm_clf), ('knn', knn_clf)], voting='soft')

In [13]:
accuracy = accuracy_score(y_val, y_pred)
print("Validation Accuracy of Ensemble Classifier:", accuracy)
conf_mat = confusion_matrix(y_val, y_pred)
print("Confusion Matrix:")
print(conf_mat)
class_report = classification_report(y_val, y_pred)
print("Classification Report:")
print(class_report)

Validation Accuracy of Ensemble Classifier: 0.9649122807017544
Confusion Matrix:
[[39  4]
 [ 0 71]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.91      0.95        43
           1       0.95      1.00      0.97        71

    accuracy                           0.96       114
   macro avg       0.97      0.95      0.96       114
weighted avg       0.97      0.96      0.96       114



## Averaging Ensemble Model

In [14]:
y_pred_rf_proba = rf_clf.predict_proba(x_val)
y_pred_svm_proba = svm_clf.predict_proba(x_val)
y_pred_knn_proba = knn_clf.predict_proba(x_val)
avg_pred_proba = (y_pred_rf_proba + y_pred_svm_proba + y_pred_knn_proba) / 3
y_pred_avg = np.argmax(avg_pred_proba, axis=1)

In [15]:
accuracy_avg = accuracy_score(y_val, y_pred_avg)
print(f"Accuracy of Averaging Ensemble Model: {accuracy_avg}")
conf_mat_avg = confusion_matrix(y_val, y_pred_avg)
print(f"Confusion Matrix for Averaging Ensemble Model:\n{conf_mat_avg}")
class_report_avg = classification_report(y_val, y_pred_avg)
print(f"Classification Report for Averaging Ensemble Model:\n{class_report_avg}")

Accuracy of Averaging Ensemble Model: 0.9649122807017544
Confusion Matrix for Averaging Ensemble Model:
[[39  4]
 [ 0 71]]
Classification Report for Averaging Ensemble Model:
              precision    recall  f1-score   support

           0       1.00      0.91      0.95        43
           1       0.95      1.00      0.97        71

    accuracy                           0.96       114
   macro avg       0.97      0.95      0.96       114
weighted avg       0.97      0.96      0.96       114



## Weighted Averaging Ensemble Model


In [16]:
rf_weight = 0.4
svm_weight = 0.3
knn_weight = 0.3
weighted_avg_pred_proba = (rf_weight * y_pred_rf_proba + svm_weight * y_pred_svm_proba + knn_weight * y_pred_knn_proba)
y_pred_weighted_avg = np.argmax(weighted_avg_pred_proba, axis=1)

In [17]:
accuracy_weighted_avg = accuracy_score(y_val, y_pred_weighted_avg)
print(f"Accuracy of Weighted Averaging Ensemble Model: {accuracy_weighted_avg}")
conf_mat_weighted_avg = confusion_matrix(y_val, y_pred_weighted_avg)
print(f"Confusion Matrix for Weighted Averaging Ensemble Model:\n{conf_mat_weighted_avg}")
class_report_weighted_avg = classification_report(y_val, y_pred_weighted_avg)
print(f"Classification Report for Weighted Averaging Ensemble Model:\n{class_report_weighted_avg}")

Accuracy of Weighted Averaging Ensemble Model: 0.9649122807017544
Confusion Matrix for Weighted Averaging Ensemble Model:
[[39  4]
 [ 0 71]]
Classification Report for Weighted Averaging Ensemble Model:
              precision    recall  f1-score   support

           0       1.00      0.91      0.95        43
           1       0.95      1.00      0.97        71

    accuracy                           0.96       114
   macro avg       0.97      0.95      0.96       114
weighted avg       0.97      0.96      0.96       114

